# Generated by Django 2.1.5 on 2019-02-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter', models.CharField(max_length=1)),
                ('english', models.CharField(max_length=50)),
                ('phonetic_symbol', models.CharField(max_length=50)),
                ('chinese', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordDbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='word_db_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='train.WordDbType'),
        ),
    ]
