# Generated by Django 2.1.5 on 2019-02-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('word_db_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='train.WordDbType')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='first_letter',
            field=models.CharField(max_length=50),
        ),
    ]
