# Generated by Django 2.1.2 on 2019-03-04 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0004_auto_20190223_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='复习时间')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('mastery_level', models.FloatField(default=50, verbose_name='掌握程度')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='train.Word')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdbword',
            name='english',
        ),
        migrations.RemoveField(
            model_name='userdbword',
            name='player',
        ),
        migrations.DeleteModel(
            name='UserDbWord',
        ),
    ]
